name: Python wheels

on:
  push:
    branches: [ $default-branch ]
  workflow_dispatch:


#  release:
#    types:
#      - created

jobs:
  wheels:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade setuptools wheel build auditwheel

    - name: Build wheels
      run: python -m build --wheel

    - name: Fix wheels
      run: python -m auditwheel repair dist/*.whl --plat manylinux2014_x86_64

    - uses: actions/upload-artifact@v2
      with:
        name: wheel-linux-${{matrix.python-version}}
        path: wheelhouse/*.whl

  dist:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade setuptools wheel build

    - name: Build source dist
      run: python -m build --sdist

    - uses: actions/upload-artifact@v2
      with:
        name: sources
        path: dist/*

  deploy:
    runs-on: ubuntu-latest
    needs: ["wheels", "dist"]
    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install twine
    - name: Download artifacts
      uses: actions/download-artifact@v2
    - name: Build and publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        twine upload dist/* wheelhouse/* --repository testpypi